version: "3.1"

networks:
  proxy-net:
    external:
      name: proxy-net

services:
  hero-scrape-web:
    container_name: hero-scrape-web
    networks:
      - proxy-net
    build: .
    restart: always
    environment:
      - VIRTUAL_HOST=hero-scrape.viktor-braun.de
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=hero-scrape.viktor-braun.de
      - LETSENCRYPT_EMAIL=mail@viktor-braun.de
